version: '3.8'
services:
  ecommerce-back:
    container_name: ecommerce-back-dev
    image: ecommerce-back
    restart: always
    build:
      context: .
      dockerfile: ./environment/dev/Dockerfile
    volumes:
      - ecommerce-back-dev-data:/app/uploads
    ports:
      - '40028:40028'
    networks:
      - master_network

networks:
  master_network:
    external: true

volumes:
  ecommerce-back-dev-data:
